version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=embeddings
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - orchestrator-network

  orchestrator:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3001:3001"  # Expose outside the container
    environment:
      - API_KEY=your-shared-api-key
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=embeddings
      - WORKER_LOCATIONS=10.0.0.3:3000
      - BATCH_SIZE=10
      - MODEL_ID=bge-small-en-v1.5
      - PIPELINE_INTERVAL_SECS=60
      - PORT=3001
    volumes:
      - ./models:/app/models
    depends_on:
      - postgres
    networks:
      - orchestrator-network

networks:
  orchestrator-network:
    driver: bridge

volumes:
  postgres-data: