services:
  inference-worker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # API port
      - "3001:3001"  # Metrics port
    environment:
      - MODEL_ID=bge-small-en-v1.5
      - LOG_LEVEL=debug
      - API_KEY=fart
    volumes:
      - ./models:/app/models  # Mount models directory for development
    deploy:
      resources:
        reservations:
          devices:
            - driver: gpu
              capabilities: [gpu]